### ISSUE TITLE
入門06 - [ToDoアプリのタスク作成機能を作る]について

### ISSUE THREAD

**Issue by Somahc** [eguchi244/public-zenn-docs#1]
こんにちは、eguchi244さんの記事でLaravelを勉強させていただいています。素敵な記事を書いてくださりありがとうございます！

入門06についてなのですが、もしかしたら誤植があるかもしれません。タスク一覧ページのからタスク作成ページに遷移させるためのボタンについて、
```php
<a href="{{ route('tasks.create', ['id' => $folder_id]) }}" class="btn btn-default btn-block">
    タスクを追加する
</a>
```
との記述がありますが、$folder_idは定義させていないといった旨のエラーが出てしまいます。TaskController.phpのindex()関数内のreturn viewの部分を
```php
'current_folder_id' => $id, // 変更前
'current_folder_id' => $current_folder->id, // 変更後
```
のように変更し、index.blade.phpの該当部分を
```php
<a href="{{ route('tasks.create', ['id' => $current_folder_id]) }}" class="btn btn-default btn-block">
   タスクを追加する
</a>
```
とすることで、正常に動作することを確認しました。

私がただ単に前の記事での変更を見落としてハマっただけなら良いのですが、もしかしたら誤植かもしれないと思い報告させていただきます。私のミスであれば無視してください。

**Comment by Somahc** [comment]
追加でテストケース"due_date_should_be_date"は、
```php
$response->assertSessionHasErrors([
    'due_date' => '期限日 には今日以降の日付を入力してください。',
]);
```
のように"今日以降の"を追加するべきかもしれないです！

**Comment by eguchi244** [comment]
この度は、「Laravel入門 - Laravelを使ってみよう!」をご利用ありがとうございます。
まずは、ご不便をおかけしたことをお詫び申し上げます。

ご指摘の部分を拝見させていただきました。
原因は執筆中ということもあり相応しくないと感じた部分を私がを修正していたためです。
特に `'current_folder_id'` の部分は他のパラメーターとの統一感を損なっていました。
おそらく、Somahcさんがご覧になったのはその修正途中の記事だったのだと思います。

現在の記事では該当の部分は下記のように修正してありますのでご確認いただければと思います。

[index.blade.php]
```
<a href="{{ route('tasks.create', ['id' => $folder_id]) }}" class="btn btn-default btn-block">
    タスクを追加する
</a>
```
このように `$current_folder_id` → `$folder_id` に変更されています。

[TaskController.php]
```
  public function index(int $id)
  {
      [中略]
      return view('tasks/index', [
          'folders' => $folders,
          'folder_id' => $folder->id,
          'tasks' => $tasks
      ]);
  }
```
このように `'current_folder_id'` → `'folder_id'` に変更されています。
上記のように「current_folder_id」としていた部分は変更されています。

対処法としては記事の末尾にある各ブランチのコードを確認してもうらうのが最良かと思います。
この方法であればその章に記述されていない修正されている部分のコードも確認できるからです。
そして indexメソッド はまさにご指摘の通りに「過去に記述されて修正されている部分」です。
Somahcさんの想像は見事に的中されておりました。

少しでも良いものを皆様に提供したいという思いから修正をさせていただいております。
ご不便をおかけしますが何卒、ご理解いただければと思っております。

また、テストケースはご指摘の内容を採用して記事とレポジトリに反映させていただきました。

```
$response->assertSessionHasErrors([
    'due_date' => '期限日 には今日以降の日付を入力してください。',
]);
```

今後も「Laravel入門 - Laravelを使ってみよう!」へのご利用とご意見をいただければ幸いです。

**Comment by Somahc** [comment]
迅速な対応ありがとうございます！

eguchi244さんの記事はとてもわかりやすく、laravel学習者としてはありがたい限りです。これからもよろしくお願いいたします！
